# Generated by Django 4.1.3 on 2024-09-24 09:58

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to=services.models.custom_upload_to, verbose_name='Imágen descriptiva del servicio'),
            preserve_default=False,
        ),
    ]
