# Generated by Django 4.1.3 on 2024-09-24 10:38

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Categoría de proyecto')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del cliente o compañía')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre descriptivo de la imagen')),
                ('image', models.ImageField(upload_to=main.models.custom_upload_to, verbose_name='Imagen')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Galería de proyectos',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título del proyecto')),
                ('description', models.TextField(verbose_name='Descripción del proyecto')),
                ('testimonial', models.CharField(max_length=500, verbose_name='Testimonios')),
                ('imageTestimonial', models.ImageField(blank=True, null=True, upload_to=main.models.custom_upload_to, verbose_name='Persona del testimonio')),
                ('conclusion', models.CharField(max_length=800, verbose_name='Conclusión del proyecto')),
                ('projectFinished', models.CharField(max_length=100, verbose_name='Fecha de finalización')),
                ('projectUrl', models.URLField(max_length=250, verbose_name='Enlace al proyecto')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category', models.ManyToManyField(related_name='Categorías', to='main.category', verbose_name='Categoría del proyecto')),
                ('client', models.ManyToManyField(related_name='Clientes', to='main.client', verbose_name='Cliente')),
                ('image', models.ManyToManyField(related_name='Proyectos', to='main.image')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
