# Generated by Django 4.1.3 on 2024-09-24 11:06

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gallery',
            field=models.ManyToManyField(related_name='Proyectos', to='main.image'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to=main.models.custom_upload_to, verbose_name='Imagen descriptiva'),
            preserve_default=False,
        ),
    ]
