# Generated by Django 4.1.3 on 2024-09-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training', models.CharField(max_length=100, verbose_name='Mi formación')),
                ('timeInvested', models.CharField(max_length=50, verbose_name='Tiempo invertido')),
                ('institute', models.CharField(max_length=100, verbose_name='Instituto o universidad')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educación',
            },
        ),
        migrations.CreateModel(
            name='ProffesionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100, verbose_name='Trabajo')),
                ('timeWorked', models.CharField(max_length=100, verbose_name='Tiempo trabajado')),
                ('workLocation', models.CharField(max_length=100, verbose_name='Dónde trabajé')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Experiencia profesional',
                'verbose_name_plural': 'Experiencia profesional',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mi nombre')),
                ('description', models.CharField(max_length=300, verbose_name='Mi descripción')),
                ('address', models.CharField(max_length=100, verbose_name='Mi dirección')),
                ('phone', models.CharField(max_length=15, verbose_name='Mi teléfono celular')),
                ('email', models.EmailField(max_length=100, verbose_name='Mi email')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Resumen',
                'verbose_name_plural': 'Resumen',
            },
        ),
    ]
